city: Any
scenario: Normal
riders:
  count: 3
  start: [0.0, 0.0]  
orders:
  ready_min_mu: 10
  ready_min_sigma: 5
  sla_min_low: 45
  sla_min_high: 70
zones:
  - name: baseline
    center: [0, 0]
    radius_km: 999.0
    multiplier: 1.0
    active_min: [0, 1440]