city: Kolkata
scenario: Durga Puja
riders:
  count: 3
  start: [0.0, 0.0]
orders:
  ready_min_mu: 10
  ready_min_sigma: 5
  sla_min_low: 45
  sla_min_high: 70
zones:
  - name: pandal_1
    center: [4, 3]
    radius_km: 2.0
    multiplier: 1.4
    active_min: [1140, 1380]   # 19:00–23:00
  - name: pandal_2
    center: [-3, 4]
    radius_km: 2.0
    multiplier: 1.4
    active_min: [1140, 1380]
  - name: night_crowd
    center: [0, 0]
    radius_km: 999.0
    multiplier: 1.2
    active_min: [1140, 1380]